logsBucket: 'gs://bucket67ut'

steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd environments/dev
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd environments/prod
      fi
      terraform init

- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd environments/dev
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd environments/prod
      fi
      terraform plan

- id: 'terraform apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd environments/dev
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd environments/prod
      fi
      terraform apply -auto-approve
